---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: something-terrible
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - from-file: module-recipes/files.yml
  - from-file: module-recipes/fonts.yml
  - from-file: module-recipes/dnf.yml
  - from-file: module-recipes/brew.yml
  - from-file: module-recipes/kargs.yml
  - from-file: module-recipes/scripts.yml
  - from-file: module-recipes/systemd.yml
  - type: signing
